name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          git lfs install
          git lfs track "synthetic_data_generator/outputs/**"
          git lfs track "*.pt"
          git lfs track "*.onnx"
          git lfs track "*.data"
          git lfs track "*.png"
          git lfs track "*.npy"
          git add .gitattributes
          git config --global user.email "ogunodemarvellous@gmail.com"
          git config --global user.name "teewa56"
          git remote add origin https://Teewa56:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Teewa56/TGT
          git checkout -b main
          git add .
          git commit -m "Fresh clean deploy"
          git push --force origin main